services:
  mysql:
    image: mysql:8.0
    container_name: cassandra-pilot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cassandra_pilot
      MYSQL_USER: pilot_user
      MYSQL_PASSWORD: pilot_pass
    ports:
      - "0.0.0.0:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cassandra-pilot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cassandra-pilot-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: cassandra_pilot
      DB_USER: pilot_user
      DB_PASSWORD: pilot_pass
      JWT_SECRET: cassandra-pilot-secret-key-2024
      NODE_ENV: production
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cassandra-pilot-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-pilot-frontend
    ports:
      - "0.0.0.0:8088:8088"
    depends_on:
      - backend
    networks:
      - cassandra-pilot-network

volumes:
  mysql_data:

networks:
  cassandra-pilot-network:
    driver: bridge 